excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
line_length:
  - 300 # warning
  - 400 # error
disabled_rules:
  - trailing_whitespace
  - colon
  - force_cast